### ISSUE TITLE
Hardware design

### ISSUE THREAD

**Issue by ealione** [teuobk/xmas2024#1]
Quite interesting project. Are the KiCAD files available anywhere so I can try to build it.

**Comment by ghangaskan** [comment]
What you’ve done here is masterful, and I would appreciate learning by doing on this project. Thank you for documenting your design choices and thought processes. I appreciate the care with which you have built this Christmas gift.

Merry Christmas to you and yours!

**Comment by ghangaskan** [comment]
> What you’ve done here is masterful, and I would appreciate learning by doing on this project. Thank you for documenting your design choices and thought processes. I appreciate the care with which you have built this Christmas gift.
> 
> Merry Christmas to you and yours!

I recognize that on the technical description page the schematic was fuzzed out and refers to Nesota. If there is some portion that can be published to github I'd still love it but I totally get it if that is not available.

**Comment by teuobk** [comment]
> I recognize that on the technical description page the schematic was fuzzed out and refers to Nesota. If there is some portion that can be published to github I'd still love it but I totally get it if that is not available.

While I probably won't release the underlying PCB design files, you're welcome to download the schematic in PDF form; click the preview image of the schematic on the web site, or use this direct link:

https://www.keacher.com/xmas24/christmas_card_2024%20schematic%20rev%20D.pdf

**Comment by ealione** [comment]
It's a bit too complex for my rapidly fleeting ee knowledge anyway. Great work though.
