### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [teuobk/xmas2024#2]
Hello!

I found this amazing project from https://hackaday.com/2024/12/19/where-this-xmas-cards-going-we-dont-need-batteries/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and PCB hardware files (if they will be added) in any purpose?
It would be great to see any popular open source license.

**Comment by teuobk** [comment]
Added. Thanks!

**Comment by vazhnov** [comment]
BSD-3-Clause license — amazing! Thank you!
